---
apiVersion: v1
kind: Service
metadata:
  name: workers-service
  labels:
    app: workers-service
spec:
  ports:
    - port: 80
      name: worker
  clusterIP: None
  selector:
    app: workers-service
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: worker
  labels:
    app: workers-service
spec:
  serviceName: "workers-service"
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: workers-service
  replicas: 3
  template:
    metadata:
      labels:
        app: workers-service
    spec:
      containers:
        - name: workers-service
          image: liabifano/hogwild:latest
          env:
            - name: N_WORKERS
              value: "5"
            - name: RUNNING_MODE
              value: "synchronous"
            - name: DATA_PATH
              value: "my-path"
          ports:
            - containerPort: 80
              name: worker
          command: ["python", "hogwild-python/src/hogwild/node.py", "80"]
          volumeMounts:
            - name: shared-volume
              mountPath: /data
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: cs449g9-scratch