---
apiVersion: v1
kind: Service
metadata:
  name: workers-service
  labels:
    app: workers-service
spec:
  ports:
    - port: 80
      name: worker
  clusterIP: None
  selector:
    app: workers-service
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: worker
  labels:
    app: workers-service
spec:
  serviceName: "workers-service"
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: workers-service
  replicas: 5
  template:
    metadata:
      labels:
        app: workers-service
    spec:
      containers:
        - name: workers-service
          image: liabifano/hogwild:latest
          env:
            - name: N_WORKERS
              valueFrom:
                configMapKeyRef:
                  name: hogwild-config
                  key: replicas
            - name: RUNNING_MODE
              valueFrom:
                configMapKeyRef:
                  name: hogwild-config
                  key: running_mode
            - name: DATA_PATH
              valueFrom:
                configMapKeyRef:
                  name: hogwild-config
                  key: data_path
            - name: WHERE
              valueFrom:
                configMapKeyRef:
                  name: hogwild-config
                  key: running_where
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          ports:
            - containerPort: 80
              name: worker
          command: ["python", "hogwild-python/src/hogwild/super_node.py", "80"]
          volumeMounts:
            - name: shared-volume
              mountPath: /data
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: cs449g9-scratch